version: "3.7"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: woofer
      POSTGRES_USER: woofer
      POSTGRES_PASSWORD: woofwoof
    volumes:
      - "./db/up.sql:/docker-entrypoint-initdb.d/up.sql"
    ports:
      - "5432:5432"
  nats:
    image: nats-streaming:linux
    restart: always
